language: ruby
jobs:
  include:
  - rvm: 2.7.1
    before_script: gem install openssl
    cache: bundler
  - rvm: jruby
    before_script: gem install jruby-openssl
script: bundle exec rake
notifications:
  email:
    recipients:
    - spacefugitive@gmail.com
    on_failure: change
    on_success: never
deploy:
  provider: rubygems
  api_key:
    secure: OG5ME4JIOOy12E2cRF/b0ZqBoIpQ8TA2Cv0vLFwSKsxLRWyiImAoGe1PkQVbZYieajpepTs4Wyh801nYNqsBSzwKLxdKU/zwULlz1y+/o9n3UTOQAVb9seTcZmALQOuN/sERlyOQ5llJZZP8VQdbEj1VmLPKD9ZHqManAQwTMgDDNsGoQ0hysqmAVjXzOmXmzLWZ+L4MBqniZnqn/NRZoEzmWxoivr7T8cJjvspNqKAbrdTgSrEd0iCP0rjcbMkm6yWjAEZQbCKKF/Ou2FuRU1U2WWoO/dvD2PNTvMNHoCGiueCga7MvcFO041K6CacBaDUjCKJKYa3Wnz/LwQqnhdm0vRTxALzf68AT8n01VnWvlcrnzJCIkfOeF7/xBNQxHKJ9S0RYtPAoN1TQB3Ku49yVN6bw8gx0Z4C0N6ita2s6FhZQ6OGZiVQgLgEtlJuzrXZruKt4wdBXN5+/snzSiLfuUYrjlZuM4OlV9LEF7ogdkTKz6li6RFi/IJMlhaeBbJ8tvnn5YTDbh4w5D21IM1tGZV+sJlpgDIuEEEfficwgDh65ge0u2JEeRowmG0G1hkAL5tQMO46ky2leKmOCVEOMWMzdM3DrDxtw9mop2jXW+kAd+FlK4FGh8H5EhPqlYk7ZaTd3G2gZPlJTfTWO1t+Xy2HwshO573ZKl5vfUD8=
  on:
    tags: true
    repo: spacefugitive/telegram-auth
    branch: main
