name: ci

on:
  push:
    branches:
      - main
    paths-ignore: "README.md"

jobs:
  test:
    if: "contains(github.event.commits[0].message, '[ci skip]') == false"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7"
      - name: test
        run: bundle exec rake spec
