name: ci

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "README.md"
  push:
    paths-ignore:
      - "README.md"

jobs:
  test:
    if: "contains(github.event.commits[0].message, '[ci skip]') == false"
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.6, 2.7, jruby, truffleruby]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.7"

      - name: Install Dependencies
        run: bundle install

      - name: test
        run: bundle exec rake spec
